### ISSUE TITLE
Bug: Save shader issue

### ISSUE THREAD

**Issue by briheet** [CrossGL/crosstl#103]
Was testing out the notebook where i found this error 
![2024-08-29-08:03:53-screenshot](https://github.com/user-attachments/assets/8c4bc23a-ae46-4bde-a74a-1acc69da144e)

This works without save shader. Saw Sam add this recently.
Does this need any help ?
Read about opengl wiki for shaders. I hope its being saved in the output.metal file.

**Comment by samthakur587** [comment]
hii @briheet thanks for asking this what this `save_shader` is doing is that it will just save your output code into a file. so you can use this file for reverse translation. 

this issue has resolved in current pypl release. let's try now it will work . thanks for flagging this .
