### ISSUE TITLE
Add support for double data type at opengl backend

### ISSUE THREAD

**Issue by ashwith2427** [CrossGL/crosstl#148]

**Comment by ashwith2427** [comment]
@samthakur587 assign this issue to me

**Comment by shivangiphilic** [comment]
@samthakur587 Hello, could admin please assign me this issue? I'd like to try solving it.

**Comment by tiashamaitra** [comment]
Add support for double data type at opengl backend #148 pls assign me @samthakur587

**Comment by gjyotin305** [comment]
@NripeshN PTAL
