### ISSUE TITLE
SHIFT_RIGHT : >>

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#182]

**Comment by anshikavashistha** [comment]
@samthakur587 Please assign me

**Comment by amMistic** [comment]
@anshikavashistha if you don't mind, I'd like to work on this one?

**Comment by amMistic** [comment]
@NripeshN could you assign this to me?

**Comment by NripeshN** [comment]
Hi @amMistic @anshikavashistha 

Feel free to starting working on this issue and create a PR(even if not completely completed) and mention in the description that is closes the issues related to the PR(eg. Closes #xyz #abc ...)

**Comment by amMistic** [comment]
Hi @NripeshN, @anshikavashistha,

I'm having trouble creating test cases for this issue, as I'm not familiar with the process. Could you please provide guidance or point me in the right direction so I can learn and contribute effectively?
