### ISSUE TITLE
LOGICAL_AND" : &&

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#183]

**Comment by AtulC137** [comment]
hey hii ... i would to work on this task if possible !

**Comment by AishaRuqshan** [comment]
I would appreciate the opportunity to take on this task. Please consider assigning it to me, as I am confident in my ability to handle it effectively.

**Comment by tiashamaitra** [comment]
LOGICAL_AND" : && pls assign me @samthakur587

**Comment by thepriyanshpal** [comment]
Hi @NripeshN,

I would like to contribute to this issue by implementing support for the `LOGICAL_AND` operator in the DirectX backend. Could you please assign this issue to me?

Thank you!
