### ISSUE TITLE
DOUBLE : double

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#189]

**Comment by annu3450** [comment]
Please assign #189

**Comment by thepriyanshpal** [comment]
Hi @NripeshN,

I would like to work on this issue to add support for the `DOUBLE` data type in the DirectX backend. Could you please assign this issue to me?

Thank you!

**Comment by NripeshN** [comment]
To assign issues to yourself please read this documentation: https://github.com/CrossGL/crosstl/blob/main/CONTRIBUTING.md#-assigning-or-creating-issues

**Comment by siddharth0607** [comment]
@CrossGL-issue-bot assign me

**Comment by thepriyanshpal** [comment]
@CrossGL-issue-bot assign me

**Comment by thepriyanshpal** [comment]
@CrossGL-issue-bot assign me

**Comment by KripaAc** [comment]
@CrossGL-issue-bot assign me
