### ISSUE TITLE
switch statement

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#193]

**Comment by annu3450** [comment]
please assign #193 to me

**Comment by Skv9655** [comment]
please assign #193 to me

**Comment by abhuday-sudhir** [comment]
hi @NripeshN please assign issue #193 to me

**Comment by jercy12** [comment]
@NripeshN @samthakur587 please assign to me this Switch Statement #193 issue

**Comment by AishaRuqshan** [comment]
I would appreciate the opportunity to take on this task. Please consider assigning #193 to me, as I am confident in my ability to handle it effectively.

**Comment by thepriyanshpal** [comment]
Hi @NripeshN,

I’d like to work on this issue to implement support for the `SWITCH` statement in the DirectX backend. Could you please assign it to me?

Thank you!

**Comment by NripeshN** [comment]
To assign issues to yourself please read this documentation: https://github.com/CrossGL/crosstl/blob/main/CONTRIBUTING.md#-assigning-or-creating-issues
