### ISSUE TITLE
Add Support for SPIR-V Translation

### ISSUE THREAD

**Issue by RohithKesoju** [CrossGL/crosstl#212]
### **Problem**
The crosstl project currently lacks support for SPIR-V (Standard Portable Intermediate Representation), a widely-used shader format in the Vulkan and OpenCL ecosystems. SPIR-V acts as a binary intermediate language, bridging high-level shader code and low-level GPU instructions.

Without SPIR-V support, the utility of crosstl is limited for developers working in Vulkan-based workflows or modern graphics applications. Adding SPIR-V compatibility would unlock new use cases and attract a broader audience of developers.

### **Proposed Solution**

**SPIR-V Parsing:**
Introduce a module to parse SPIR-V binaries and convert them into the project's intermediate representation (IR).
Leverage tools like [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools) for parsing and validation.

**Intermediate Representation (IR) Adaptation:**
Extend the IR structure to support SPIR-V-specific constructs like execution modes and built-in variables.

**SPIR-V Code Generation:**
Implement a generator to convert the IR back into SPIR-V binaries, ensuring full compatibility with the SPIR-V specification.

**Integration with CLI and API:**
Update the project's CLI and API to include options for SPIR-V as an input and output language.

### **Benefits**

- **Broader Compatibility:**
Enables crosstl to support Vulkan and OpenCL developers, significantly expanding the project's audience.

- **Improved Efficiency:**
Leverages SPIR-V’s binary format for faster shader translation and optimized performance.

- **Enhanced Project Utility:**
Positions crosstl as a more versatile tool for shader translation across diverse platforms and APIs.

This feature will greatly enhance the utility of crosstl, making it a go-to solution for shader translation, especially in Vulkan-centric workflows.

**Comment by RohithKesoju** [comment]
@NripeshN please assign me this issue, I would like to solve this

**Comment by NripeshN** [comment]
> @NripeshN please assign me this issue, I would like to solve this

Hi @RohithKesoju,

This is some great initiative and really love you want to add SPIR-V support. We have a PR open already that worked on the backend I believe(https://github.com/CrossGL/crosstl/pull/125). This PR is still a work in progress, you can take over the PR and help @he11owthere either complete the PR. There are still a lot more tasks to do like adding tests for both backend and the translator in our test suite. If you have any further questions feel free to ask😁
