### ISSUE TITLE
Optimize Lexer Performance with Token Caching and Pattern Combining

### ISSUE THREAD

**Issue by Swish78** [CrossGL/crosstl#224]
## Description  
The lexer can be optimized to improve performance and reduce memory usage. This task focuses on implementing token caching, combining similar regex patterns, and caching compiled patterns.  

### Proposed Changes  
1. **Token Caching**  
   - Add a `token_cache` dictionary to reuse frequently used tokens.  
   - Introduce a `_get_cached_token` helper method to manage the cache.  

2. **Combined Regex Patterns**  
   - Group similar patterns (e.g., numbers, vectors, matrices) into combined regex patterns.  
   - Add a `COMBINED_PATTERNS` dictionary to simplify and speed up token matching.  

3. **Pattern Precompilation**  
   - Cache compiled regex patterns to avoid recompilation.  
   - Add a `_compile_patterns` method for one-time regex compilation and store patterns in `REGEX_CACHE`.  

## Files to Modify  
[crosstl/translator/lexer.py](https://github.com/CrossGL/crosstl/blob/main/crosstl/translator/lexer.py)  

---  

@NripeshN, I would love to work on this task. Let me know if it sounds good!

**Comment by raghulchandramouli** [comment]
@Swish78 can you assign me this task I think I can complete this

**Comment by SinghSahitya** [comment]
@NripeshN Hii I would like to work on this issue

**Comment by NripeshN** [comment]
To assign issues to yourself please read this documentation: https://github.com/CrossGL/crosstl/blob/main/CONTRIBUTING.md#-assigning-or-creating-issues

**Comment by AeleSahithi** [comment]
@CrossGL-issue-bot assign me

**Comment by Swish78** [comment]
@CrossGL-issue-bot assign me

**Comment by Prisha-Mordia** [comment]
@CrossGL-issue-bot assign me

**Comment by Swish78** [comment]
Hi @NripeshN,

I’ve submitted PR (#229), and all checks have passed successfully. It just needs your review.

Thank you!
