### ISSUE TITLE
Add `else if `  Conditional Statements to the translator

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#32]
To add `else if` support to CrossGL, modify the following files in the `crosstl/src/translator` directory:

- [ ] **Lexer.py**: Add token recognition for `else if`.
- [ ] **Parser.py**: Update grammar and AST to handle `else if`.
- [ ] **Directx_codegen.py**: Implement `else if` for HLSL output.
- [ ] **Metal_codegen.py**: Implement `else if` for Metal output.
- [ ] **Opengl_codegen.py**: Implement `else if` for GLSL output. 

Your contribution is appreciated! Feel free to reach out on our [Discord Server ](https://discord.com/invite/uyRQKXhcyW) if you have any query.

**Comment by AxelB1011** [comment]
Hello 👋 

Can I please take this one?

**Comment by NripeshN** [comment]
> Hello 👋 
> 
> 
> 
> Can I please take this one?

Sure thing @AxelB1011😁

**Comment by kartik-singh-droid** [comment]
Hi interested to work on this issue . So kindly assign it to me @NripeshN @niixxaaa

**Comment by Prix201** [comment]
i  would like to take on this issue if not completed yet @niixxaaa
