### ISSUE TITLE
Add `else if` Conditional Statements to the DirectX backend

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#33]
To add `else if` support to CrossGL, modify the following files in the `crosstl/src/backend/DirectX` directory:

- [ ] **DirectxLexer.py** : Add token recognition for `else if`.
- [ ] **DirectxParser.py** : Update grammar and AST to handle `else if`.
- [ ] **DirectxCrossGLCodeGen.py** : Implement `else if` for Crossgl output.

Your contribution is appreciated! Feel free to reach out on our [Discord Server ](https://discord.com/invite/uyRQKXhcyW) if you have any query.

**Comment by Proxihox** [comment]
Hi @samthakur587 , I'd like to work on this issue.

**Comment by Raghav-2903** [comment]
Hi @samthakur587 Can I work on this issue?
