### ISSUE TITLE
Add `else if` Conditional Statements to the Metal backend

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#34]
To add `else if` support to CrossGL, modify the following files in the `crosstl/src/backend/Metal` directory:

- [ ] **MetalLexer.py** : Add token recognition for `else if`.
- [ ] **MetalParser.py** : Update grammar and AST to handle `else if`.
- [ ] **MetalCrossGLCodeGen.py** : Implement `else if` for Crossgl output.

Your contribution is appreciated! Feel free to reach out on our [Discord Server ](https://discord.com/invite/uyRQKXhcyW) if you have any query.

**Comment by adityanarayanan343** [comment]
Hi I would like to work on this issue. So kindly assign me this issue

**Comment by rohansawant0735** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me? 
- Rohan

**Comment by NripeshN** [comment]
> Hi, I’d like to work on this issue. Could you please assign it to me? 
> 
> - Rohan
> 
> 

Hi @rohansawant0735 
This issue is currently being worked by @adityanarayanan343. Feel free to go through our other unassigned issues or create a new issue if you're interested in contributing to our repo😁

**Comment by revanthreddy13** [comment]
intrested to work on the isuue

**Comment by vishwa8904** [comment]
Hi I would like to work on this issue. So please kindly assign it to me #34

**Comment by kartik-singh-droid** [comment]
Hi interested to work on this issue . So kindly assign it to me  @NripeshN

**Comment by pratikmhadgut** [comment]
Hi I would like to work on this issue. So kindly assign me this issue

**Comment by Ash-creater** [comment]
I would like to work on this issue.So kindly assign me this issue.

**Comment by rishabhr03** [comment]
I woulfd like to work on this issue @NripeshN

**Comment by therishabhsharma03** [comment]
@NripeshN 
I would like to work on this issue

**Comment by faizanfayazmir1** [comment]
Hi @NripeshN @samthakur587,

I am very interested in working on this issue and would like to take it on. Could you please assign it to me?

Thank you!

Best regards,
Faizan Fayaz Mir

**Comment by shreekrsna** [comment]
Hi!! I would like to work on the above issue, so kindly assign me the task.

**Comment by shreekrsna** [comment]
Any incompleted task kindly assign it .
Thankyou

**Comment by kumVij** [comment]
I would like to work on the #34 issue , Kindly assign me the task .

**Comment by RajvanshMalhotra** [comment]
hey @NripeshN  i had been assigned this issue are there any new issues that i could  contribute to ?
