### ISSUE TITLE
add `BITWISE_AND`  Operators support at  `translator `  frontend 

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#42]
Implement the BITWISE_AND token to recognize the & operator for performing bitwise AND operations.

**Comment by NripeshN** [comment]
@Raghav-2903 will be working on this issue

**Comment by tiashamaitra** [comment]
@NripeshN      add BITWISE_AND Operators support at translator frontend assign me

**Comment by krispycake** [comment]
I would like to work on this issue. Please assign it to me.
