### ISSUE TITLE
Add Parsing for `Bitwise Shift Right` Token

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#75]
Update the parser to handle the BITWISE_SHIFT_RIGHT token, allowing it to correctly parse expressions involving the >> operator.

**Comment by anshikavashistha** [comment]
@samthakur587 May I work on this issue?

**Comment by aditya112patel** [comment]
@samthakur587 Since no one is assigned this issue, may I work on it.

**Comment by aditya112patel** [comment]
Since no one is assigned this issue, can you assign to me .
